### PR TITLE
Patch Support min Api 9 and check if holdingActivity still exist

### PR DESCRIPTION
**Pull request by ligol**

### CODE REVIEW

**Comment by ligol** [comment]
Hi,

Yes, It correct an NPE, but also a fail I did when I've added the brackets, so I think it can be useful to merge it, at least for the little fail :/ I'm going to look more on this NPE anyway.

**Comment by tbarthel-fr** [comment]
In that case it will definitively be merged (=

Stay me tunned when you will have check the source of this NPE ? Could you post a use-case which throws this Exception ?

Thanks (:

**Comment by ligol** [comment]
I can post the Exception log from the developer console, but I'm still trying to reproduce this bug. Some time it appear, on some device and some time nothing :/ If I find a way to reproduce in a sample, I definitively post it ;)

**Comment by tbarthel-fr** [comment]
Should have been fixed with : 
https://github.com/tvbarthel/BlurDialogFragment/issues/3

**Pull request closed without merging**
