### PR TITLE
Update to use the latest version of the stack blur algorithm as it wa…

### PR DESCRIPTION
**Pull request by tomafc330**
…s causing IndexArrayOutOfBoundsException.

### CODE REVIEW

**Comment by tommytcchan** [comment]
Fixes this issue which we were also seeing with our clients:

https://github.com/tvbarthel/BlurDialogFragment/issues/36

Basically it's using a version of Stack Blur that was a little outdated 

```
 // Stack Blur v1.0 from
-        // http://www.quasimondo.com/StackBlurForCanvas/StackBlurDemo.html
-        //
-        // Java Author: Mario Klingemann <mario at quasimondo.com>
-        // http://incubator.quasimondo.com
-        // created Feburary 29, 2004
-        // Android port : Yahel Bouaziz <yahel at kayenko.com>
-        // http://www.kayenko.com
-        // ported april 5th, 2012
...
```

Notice from the original code for Stack Blur, the IndexOutOfBoundsException was fixed in 08/2013:
```
19.08.2013: Added support for Alpha blurring
```

There was a library that just used that class now named (NativeStackBlur). We are now using that library.

**Comment by tommytcchan** [comment]
@vbarthel-fr Could you review this? Thanks!

**Comment by tommytcchan** [comment]
Tested with the sample app...everything works.

**Comment by tommytcchan** [comment]
@vbarthel-fr Mind reviewing this? Thanks!

**Comment by vbarthel-fr** [comment]
@tommytcchan sorry for the delay, I'm quite busy at the moment, I will definitely take a look at what you did as soon as I have some free time.

Thanks for your contribution =)

**Comment by tommytcchan** [comment]
Okay no problem thanks!

**Comment by tommytcchan** [comment]
@vbarthel-fr Hey there any updates on this?

**Comment by daanyaal** [comment]
Any update of this please? 

I'm using version 2.1.5 but still crashing with ArrayIndexOut....

**Comment by tbarthel-fr** [comment]
Hi @tommytcchan  (= 

We are finally back~~~

We are going to look at your pull request very soon!

Could you use the tvbarthel:develop as branch target?

Thanks you.

**Comment by tommytcchan** [comment]
@tbarthel-fr so this is not going in? Do you have a workaround?

**Comment by amitav13** [comment]
@tommytcchan Could you make a PR targeting the develop branch instead? Would love this change going in as well.

**Pull request closed without merging**
